### ISSUE TITLE
Creating PDF document not working

### ISSUE THREAD

**Issue by iZer000** [RythenGlyth/EbookDownloader#3]
I can't create a PDF with "Selectable text" turned on.

This is the error I get:
![Screenshot](https://github.com/RythenGlyth/EbookDownloader/assets/77457719/ba5a9602-ce2c-46b3-8f6d-6c328baf2d89)

It also does create the PDF file, but it takes up 0 bytes of storage.

**Comment by RythenGlyth** [comment]
is this fixed with commit 13a6f4b?

**Comment by iZer000** [comment]
Uhm, more or less...
![image](https://github.com/RythenGlyth/EbookDownloader/assets/77457719/b834ed4b-872e-4b0b-832c-6320cedee0b7)
I still get the same error, but four negatives give a positive, or something?
Weirdly, it still generated a working file *with* selectable text, so it kinda works?
![image](https://github.com/RythenGlyth/EbookDownloader/assets/77457719/2555fcb1-021d-4cbc-861c-3b37c9b5c109)

**Comment by RythenGlyth** [comment]
I think, they have some weird text there. Now, if it can't render text, it will throw these errors and just skip the text. Should be fine for now I suppose.
